[package]
name = "sigma"
version = "0.1.0"
authors = ["Lucas Soriano del Pino <l.soriano.del.pino@gmail.com>"]
edition = "2018"

[dependencies]
bigint = "4"
bit-vec = "0.6"
curve25519-dalek = "3"
ecdsa_fun = { git = "https://github.com/LLFourn/secp256kfun", features = ["libsecp_compat"] }
rand = "0.7"
sha2 = "0.9"