[package]
name = "sigma"
version = "0.1.0"
authors = ["Lucas Soriano del Pino <l.soriano.del.pino@gmail.com>"]
edition = "2018"

[dependencies]
ecdsa_fun = { git = "https://github.com/LLFourn/secp256kfun", features = ["libsecp_compat"] }
curve25519-dalek = "3"
rand = "0.7"